# -*- coding: utf-8 -*-
"""sde_simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LB1RRkvginmNhuvgPecqGoYdYnmzoPmS

Install Streamlit
"""

pip install numpy matplotlib streamlit

"""An Interactive App"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

st.title("Stochastic Differential Equation Simulator")
st.markdown("Simulating Geometric Brownian Motion (GBM)")

# User inputs
mu = st.slider("Drift (μ)", -1.0, 1.0, 0.1)
sigma = st.slider("Volatility (σ)", 0.1, 2.0, 0.5)
T = st.slider("Time Horizon (T)", 1.0, 5.0, 2.0)
N = st.slider("Number of Steps (N)", 100, 1000, 500)
M = st.slider("Number of Paths (M)", 1, 10, 3)

# Simulation
dt = T / N
t = np.linspace(0, T, N)
paths = np.zeros((M, N))
paths[:, 0] = 1 # Initial value

for i in range(1, N):
    Z = np.random.normal(0, 1, M)
    paths[:, i] = paths[:, i-1] * np.exp((mu - 0.5 * sigma**2) * dt + sigma * np.sqrt(dt) * Z)

# Plotting
fig, ax = plt.subplots()
for i in range(M):
    ax.plot(t, paths[i])
ax.set_title("Geometric Brownian Motion Paths")
ax.set_xlabel("Time")
ax.set_ylabel("Value")
st.pyplot(fig)